Phantom types
exercism/gleam pull request #340
Opened 2023-09-07 13:28 UTC by lpil

2023-09-07 14:47 UTC, hayleigh-dot-dev requested changes

2023-09-07 14:47 UTC, hayleigh-dot-dev commented on concepts/phantom-types/introduction.md
> +Phantom types are types are type parameters of a custom type that are not used in any of the value constructors of that type.
```diff
- Phantom types are types are type parameters
+ Phantom types are type parameters
```

2023-09-07 14:47 UTC, hayleigh-dot-dev commented on concepts/phantom-types/introduction.md
> +A function can also be written to ensure that two length values are of the same unit, by using the same type variable for both.
I think this can be made clearer by also showing a snippet of code that _won't_ work. Because phantom types don't have any runtime representation it can be really confusing for folks to really work out how/why they work so examples of things that don't work are super helpful.

2023-09-07 14:47 UTC, hayleigh-dot-dev commented on concepts/phantom-types/introduction.md
I've heard there's a really [cool blog post](https://hayleigh-dot-dev.github.io/blog/phantom-types-in-gleam/) out there that explains phantom types too if people wanted to read more.

2023-09-07 14:48 UTC, lpil commented on concepts/phantom-types/introduction.md
oooh I can add it to the links section

2023-09-07 14:51 UTC, hayleigh-dot-dev submitted a review, later dismissed

2023-09-07 14:51 UTC, hayleigh-dot-dev commented on exercises/concept/sticker-shop/.docs/hints.md
> +- The `Money` type should have a type parameter for the currency.
Let's make this clearer: 

```diff
- The `Money` type should have a type parameter for the currency.
+ The `Money` type should have a phantom type parameter for the currency.
```

2023-09-07 14:51 UTC, hayleigh-dot-dev commented on exercises/concept/sticker-shop/.docs/instructions.md
> +total([euro(120), euro(200), yen(145)])
This can't possibly type check.

2023-09-07 14:52 UTC, hayleigh-dot-dev commented on exercises/concept/sticker-shop/.docs/instructions.md
> +total([euro(120), euro(200), yen(145)])
I find this super ironic given my other comment on adding an example of things that _wont_ work because its a bit abstract 😅

2023-09-08 16:34 UTC, lpil commented on exercises/concept/sticker-shop/.docs/instructions.md
> +total([euro(120), euro(200), yen(145)])
ahaha oops

2023-09-08 17:29 UTC, merged