Rejig formatting
exercism/gleam pull request #95
Opened 2022-10-01 18:57 UTC by lpil

2022-10-02 13:06 UTC, massivefermion approved these changes

2022-10-02 13:24 UTC, massivefermion commented on exercises/practice/bowling/.meta/example.gleam
> +              |> list.map(add_roll_to_frame(knocked_pins)),
it seems what you're doing here is `game.frames |> list.map(add_roll_to_frame(knocked_pins))`, which means instead of a function, you're trying to give the return value of `add_roll_to_frame` to `list.map`, except that you're not giving a frame to `add_roll_to_frame` as the first argument. So I think this should be left as it was.

2022-10-02 13:33 UTC, massivefermion requested changes
see comment on line 123 in example.gleam

2022-11-04 19:57 UTC, massivefermion commented
Sorry, but I'm not sure what we're waiting for here. Should I do something?

2022-11-04 21:45 UTC, lpil commented
Hi @massivefermion ! I'm not sure either. I can't merge for some reason, I'm not sure who I am waiting on for a review.

@exercism/gleam anyone else a member of this group? :)

2022-11-06 01:17 UTC, SleeplessByte approved these changes

2022-11-06 01:17 UTC, SleeplessByte commented
@lpil I'm not but as you're just there by yourself, I do have rights! 

Merged this 🚀 . Feel free to tag me whenever, and / or Erik or Jeremy.

2022-11-06 01:18 UTC, merged